version: 2

references:
  workspace_root: &workspace_root ~/repo

  container_config: &container_config
    docker:
      - image: circleci/node:latest

  dep_cache_key: &dep_cache_key deps-{{ checksum "yarn.lock" }}
  dep_backup_cache_key: &dep_backup_cache_key deps

  restore_deps: &restore_deps
    restore_cache:
      keys:
        - *dep_cache_key
        - *dep_backup_cache_key

  publish_test_results: &publish_test_results
    store_test_results:
      path: ./

  store_test_results: &store_test_results
    store_artifacts:
      path: xunit.xml
      prefix: tests

  store_coverage_results: &store_coverage_results
    run:
      name: Upload coverage report
      command: yarn codecov-upload
      working_directory: *workspace_root

jobs:
  build:
    <<: *container_config

    working_directory: *workspace_root

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
            - *dep_backup_cache_key

      - run: yarn install

      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  test:
    <<: *container_config

    working_directory: *workspace_root

    steps:
      - checkout

      - *restore_deps

      - run: yarn coverage

      - *publish_test_results
      - *store_test_results
      - *store_coverage_results

  lint:
    <<: *container_config

    working_directory: *workspace_root

    steps:
      - checkout

      - *restore_deps

      - run: yarn lint

  find_circular_dependencies:
    <<: *container_config

    working_directory: *workspace_root

    steps:
      - checkout

      - *restore_deps

      - run: yarn find-circular-dependencies

  flow:
    <<: *container_config

    working_directory: *workspace_root

    steps:
      - checkout

      - *restore_deps

      - run: yarn flow --max-workers 1

workflows:
  version: 2

  build_and_test:
    jobs:
      - build

      - find_circular_dependencies:
          requires:
            - build

      - test:
          requires:
            - build

      - lint:
          requires:
            - build

      - flow:
          requires:
            - build
